Update entrypoint

diff --git a/docker/entrypoint b/docker/entrypoint
--- a/docker/entrypoint
+++ b/docker/entrypoint
@@ -7,7 +7,7 @@ if [ -z "${otrl_service_name+x}" ]; then
  exit 1
 fi
 
-export NODE_IP=`ip route | awk '/default/ { print $3 }'`
+#export NODE_IP=`ip route | awk '/default/ { print $3 }'`
 
 #Generate the ${otrl_service_name} config file
 mkdir -p /etc/${otrl_service_name}/conf.d/
@@ -19,21 +19,21 @@ if [ $? -ne "0" ]; then
 fi
 
 #Import RMQ certs
-cert_passphrase=`cat /run/secrets/rabbitmq_key_passphrase`
-mkdir -p /etc/rabbitmq/client-ssl
-keytool -import -noprompt -storepass $cert_passphrase -keystore /etc/rabbitmq/client-ssl/trustStore -file /run/secrets/rabbitmq_server_cert
+#cert_passphrase=`cat /run/secrets/rabbitmq_key_passphrase`
+#mkdir -p /etc/rabbitmq/client-ssl
+#keytool -import -noprompt -storepass $cert_passphrase -keystore /etc/rabbitmq/client-ssl/trustStore -file /run/secrets/rabbitmq_server_cert
 
-if [ $? -ne "0" ]; then
- echo "Failed to import the RabbitMQ key."
- exit 1
-fi
+#if [ $? -ne "0" ]; then
+# echo "Failed to import the RabbitMQ key."
+# exit 1
+#fi
 
-if [ ! -f "/etc/rabbitmq/client-ssl/keycert.p12" -a -f "/run/secrets/rabbitmq_client_p12" ]; then
- cp /run/secrets/rabbitmq_client_p12 /etc/rabbitmq/client-ssl/keycert.p12
-else
- echo "Couldn't find the RabbitMQ client certificate."
- exit
-fi
+#if [ ! -f "/etc/rabbitmq/client-ssl/keycert.p12" -a -f "/run/secrets/rabbitmq_client_p12" ]; then
+# cp /run/secrets/rabbitmq_client_p12 /etc/rabbitmq/client-ssl/keycert.p12
+#else
+# echo "Couldn't find the RabbitMQ client certificate."
+# exit
+#fi
 
 
 if [ "$SERVICE_LOG_LEVEL" ]; then
